version: '3'

services:
  flask-service:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - /home/lyle/app/web/.env